---
jobs:
- name: deploy-development-credhub
  plan:
  - aggregate:
    - get: credhub-release
    - get: credhub-manifests-development
    - get: terraform-yaml
      resource: terraform-yaml-development
      trigger: true
- name: acceptance-tests-development
  plan:
  - aggregate:
    - get: master-bosh-root-cert
    - get: credhub-acceptance-tests
      trigger: true

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: credhub-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/credhub-acceptance-tests
- name: credhub-deployment-development
  type: bosh-deployment
  source:
    target: {{development-bosh-target}}
    client: {{development-bosh-client}}
    client_secret: {{development-bosh-client-secret}}
    ca_cert: {{bosh-ca-cert}}
    deployment: credhub-development
- name: credhub-manifests-development
  type: git
  source:
    uri: {{credhub-manifest-git-url}}
    branch: {{credhub-manifest-git-branch-development}}
- name: credhub-release
  type: git
  source:
    uri: {{credhub-release-git-url}}
    branch: master
- name: master-bosh-root-cert
  type: s3-iam
  source:
    bucket: {{cf-private-production-bucket}}
    region_name: {{aws-region}}
    versioned_file: master-bosh.crt
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}
- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
- name: terraform-yaml-development
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file-development))
    region_name: ((aws-region))
